
spring:
    h2 : 
      console : 
        enabled: true # h2 setting
    thymeleaf:
        prefix : classpath:templates/
        suffix : .html
        cache : false
    jpa:
        properties : 
          hibernate : 
            format_sql : true # 압축된 쿼리를 읽기 좋게 포멧
            ddl-auto: create # 서버 시작에 테이블 생성
            
logging:
  level: # 각 package 별로 로깅 레벨을 지정
    org.springframework.web : debug
    org.hibernate.SQL: debug            # 로그 형식으로 쿼리 보여주기
    sql: error
    jdbc: off
    jdbc.sqlonly: debug 
  file : /Users/Logs/java-spring-log # 로깅 파일 위치
  file.max-history: 9999999 # 로그 파일 삭제 주기
  file.max-size : 100MB # 로그 파일 하나당 최대 파일 사이즈

spring.datasource.url: jdbc:h2:mem:testdb
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

# Orcale / myBatis 설정 참고사이트 : https://youngjinmo.github.io/2020/10/springboot-mybatis-oracle/
# 테이블 생성 : 참고사이트2 https://hanhyx.tistory.com/39 